### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Karp7577** [KrisCris/Palworld-Pal-Editor#61]
Virustotal checked file as virus

**Comment by KrisCris** [comment]
To make you guys life easier, I bundled all the python code into a single exe using pyinstaller, so you don't need to install python and run python xxx.py. The pyinstaller's self extracting behavior is similar to how virus extract their code, that's why the exe got flagged.

But I assure the executable is 100% safe and is build automatically via GitHub Action workflow using code in this repo.

If you are still concerned about the virus thing, you can alternatively install via pypi or run the code manually.
